### ISSUE TITLE
Question on Implementation

### ISSUE THREAD

**Issue by p5a0u9l** [ali20480/RadarDetector#1]
Hello Ali, great job with the paper! I have a question for you. In the `AD_detect` methods, the line
```python
Jp = np.dot(np.eye(inpt.shape[0]), inpt[:, n])
```
Doesn't taking dot product `I*v`, with Identity matrix on the left simply return `v` ? that is, I think in all cases 
```python
Jp == inpt[:, n]
```
thank you!

**Comment by p5a0u9l** [comment]
I thought of another question for you :) 

On this line:
```python
            #get the detected indexes   
            detected_idx = np.unique(np.argwhere(detections == 1)[:,0])
```
Since you are only selecting the first column the results of the call to `AD_detects2`, there is no need to iterate over the other columns in the feature space. In `AD_detect2`, you are looping and computing threshold crossings for each `i` in `range(D)`, however, you're only using `i==0` after. 

Is there a reason for this that I'm missing?

**Comment by p5a0u9l** [comment]
Ahh. Never mind, second question answered. The equality is over all columns of `detections`, and the `[:, 0]` is selecting the index into the range profile where the threshold crossing occurred.

**Comment by ali20480** [comment]
Hi Paul, thanks for reaching out. Indeed, I don't know why I left this identity matrix in the code, guess I was trying something and since it was not causing issues, it was ignored. You can remove it of course.
Best regards.
